import io
from typing import List, Dict, Any, Optional
import pandas as pd


def _table_data_from_result(result: Dict[str, Any], max_rows: int = 20):
    if not result or not result.get("columns") or not result.get("data"):
        return [["No data"]], ["No data"]
    cols = result["columns"][:8]  # cap cols
    rows = result["data"][:max_rows]
    # rows may be list of dicts or list of lists
    if rows and isinstance(rows[0], dict):
        table = [cols] + [[str(r.get(c, "")) for c in cols] for r in rows]
    else:
        table = [cols] + [[str(v) for v in row[: len(cols)]] for row in rows]
    return table, cols


def dashboard_to_pdf(dashboard: Dict[str, Any], share_url: Optional[str] = None) -> io.BytesIO:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.enums import TA_CENTER, TA_LEFT
    from reportlab.lib.colors import HexColor, whitesmoke, black
    from reportlab.platypus import (
        SimpleDocTemplate,
        Paragraph,
        Spacer,
        Table,
        TableStyle,
        PageBreak,
        Image,
    )
    from reportlab.lib import colors

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=14 * mm,
        bottomMargin=14 * mm,
        title=dashboard.get("name", "Dashboard"),
        author="InsightAgent",
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "TitleCustom",
        parent=styles["Title"],
        fontSize=22,
        textColor=HexColor("#0f172a"),
        alignment=TA_CENTER,
        spaceAfter=6,
    )
    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontSize=9,
        textColor=HexColor("#64748b"),
        alignment=TA_CENTER,
        spaceAfter=12,
    )
    heading_style = ParagraphStyle(
        "HeadingCustom",
        parent=styles["Heading2"],
        fontSize=13,
        textColor=HexColor("#0f172a"),
        spaceBefore=14,
        spaceAfter=6,
    )
    normal_style = styles["Normal"]
    small_style = ParagraphStyle(
        "Small", parent=styles["Normal"], fontSize=7.5, textColor=HexColor("#475569")
    )
    # Build story
    story = []
    # Cover
    story.append(Paragraph(dashboard.get("name", "Dashboard"), title_style))
    desc = dashboard.get("description") or "Generated by InsightAgent — AI Data Analyst"
    story.append(Paragraph(desc, subtitle_style))
    import datetime

    story.append(
        Paragraph(
            f"Dataset {dashboard.get('dataset_id','')} • {len(dashboard.get('widgets',[]))} widgets • {datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
            subtitle_style,
        )
    )
    if share_url:
        story.append(Paragraph(f'<link href="{share_url}">{share_url}</link>', small_style))
    story.append(Spacer(1, 6 * mm))

    widgets = dashboard.get("widgets", [])
    if not widgets:
        story.append(Paragraph("No widgets in this dashboard.", normal_style))
    else:
        for idx, w in enumerate(widgets, 1):
            # Widget title
            title = w.get("title") or w.get("query") or f"Widget {idx}"
            story.append(Paragraph(f"{idx}. {title}", heading_style))
            q = w.get("query") or ""
            if q:
                story.append(Paragraph(f"<i>{q[:180]}</i>", small_style))
                story.append(Spacer(1, 2 * mm))
            # Chart placeholder — try to render PNG if kaleido available
            chart = w.get("chart")
            if chart:
                # Try to write image; if kaleido missing, just show text
                try:
                    import plotly.graph_objects as go
                    import plotly.io as pio

                    fig = go.Figure(chart)
                    # Kaleido path: we need tempfile
                    import tempfile
                    from pathlib import Path

                    with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
                        tmp_path = Path(tmp.name)
                    try:
                        # This requires kaleido engine
                        pio.write_image(fig, tmp_path, format="png", width=700, height=350, scale=1)
                        # Add to PDF
                        story.append(Image(str(tmp_path), width=160 * mm, height=80 * mm))
                    except Exception as e:
                        # No kaleido — show placeholder text
                        story.append(
                            Paragraph(
                                f'<font color="#64748b">Chart: {chart.get("layout",{}).get("title",{}).get("text","Chart")} — view interactive at {share_url or "dashboard"}.</font>',
                                small_style,
                            )
                        )
                        if tmp_path.exists():
                            tmp_path.unlink(missing_ok=True)
                    else:
                        if tmp_path.exists():
                            tmp_path.unlink(missing_ok=True)
                except Exception:
                    story.append(
                        Paragraph(
                            '<font color="#64748b">Chart image not available — install kaleido for PNG.</font>',
                            small_style,
                        )
                    )
                story.append(Spacer(1, 3 * mm))

            # Table
            result = w.get("result")
            if result:
                table_data, cols = _table_data_from_result(result, max_rows=20)
                # Style table
                # Estimate col widths
                ncols = len(table_data[0]) if table_data else 1
                total_w = 174 * mm
                col_w = total_w / max(ncols, 1)
                # Truncate long cell values
                table_data = [
                    [(str(c)[:40] + "…" if len(str(c)) > 40 else str(c)) for c in row]
                    for row in table_data
                ]
                t = Table(table_data, colWidths=[col_w] * ncols, repeatRows=1)
                header_bg = HexColor("#0f172a")
                t.setStyle(
                    TableStyle(
                        [
                            ("BACKGROUND", (0, 0), (-1, 0), header_bg),
                            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                            ("FONTSIZE", (0, 0), (-1, 0), 7),
                            ("FONTSIZE", (0, 1), (-1, -1), 6.5),
                            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                            ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
                            ("ALIGN", (0, 0), (-1, -1), "LEFT"),
                            ("GRID", (0, 0), (-1, -1), 0.4, HexColor("#e2e8f0")),
                            ("BACKGROUND", (0, 1), (-1, -1), colors.white),
                            (
                                "ROWBACKGROUNDS",
                                (0, 1),
                                (-1, -1),
                                [colors.white, HexColor("#f8fafc")],
                            ),
                            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                            ("LEFTPADDING", (0, 0), (-1, -1), 4),
                            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
                            ("TOPPADDING", (0, 0), (-1, -1), 3),
                            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                        ]
                    )
                )
                story.append(t)
                # Rows count caption
                rows = result.get("rows", len(table_data) - 1)
                trunc = result.get("truncated", False)
                caption = f"{rows} rows" + (
                    " (truncated, showing 20)" if trunc and rows > 20 else ""
                )
                story.append(
                    Paragraph(f'<font color="#64748b" size=7>{caption}</font>', small_style)
                )
            else:
                story.append(Paragraph("<i>No table result</i>", small_style))
            story.append(Spacer(1, 4 * mm))
            # Avoid overly long PDF: page break every 3 widgets
            if idx % 3 == 0 and idx != len(widgets):
                story.append(PageBreak())

    # Footer note
    story.append(Spacer(1, 8 * mm))
    story.append(
        Paragraph(
            "Generated by InsightAgent — open-source AI Data Analyst (MIT). Shares are read-only; data stays on your server.",
            small_style,
        )
    )
    doc.build(story)
    buf.seek(0)
    return buf


def report_to_pdf(
    report: Dict[str, Any],
    dashboard: Optional[Dict[str, Any]] = None,
    share_url: Optional[str] = None,
) -> io.BytesIO:
    # Report has blocks: [{type: "widget"|"markdown", widget_id|text}]
    # For PDF we reuse dashboard_to_pdf but interleave markdown
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.colors import HexColor
    from reportlab.lib.units import mm
    from reportlab.platypus import (
        SimpleDocTemplate,
        Paragraph,
        Spacer,
        Table,
        TableStyle,
        PageBreak,
        Image,
    )
    from reportlab.lib import colors
    import datetime

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=14 * mm,
        bottomMargin=14 * mm,
        title=report.get("name", "Report"),
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "TitleCustom", parent=styles["Title"], fontSize=22, textColor=HexColor("#0f172a")
    )
    heading_style = ParagraphStyle(
        "HeadingCustom",
        parent=styles["Heading2"],
        fontSize=12,
        textColor=HexColor("#0f172a"),
        spaceBefore=10,
    )
    normal_style = styles["Normal"]
    small_style = ParagraphStyle(
        "Small", parent=styles["Normal"], fontSize=7.5, textColor=HexColor("#64748b")
    )
    story = []
    story.append(Paragraph(report.get("name", "Report"), title_style))
    if report.get("description"):
        story.append(Paragraph(report["description"], small_style))
    story.append(
        Paragraph(
            f"{datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')} • {len(report.get('blocks',[]))} blocks",
            small_style,
        )
    )
    story.append(Spacer(1, 6 * mm))
    # Map widget_id to widget
    widget_map = {}
    if dashboard:
        for w in dashboard.get("widgets", []):
            widget_map[w["id"]] = w
    for block in report.get("blocks", []):
        if block.get("type") == "markdown":
            text = block.get("text", "")
            # Convert markdown-ish to reportlab: handle # headings
            for line in text.split("\n"):
                if line.startswith("### "):
                    story.append(Paragraph(line[4:], heading_style))
                elif line.startswith("## "):
                    story.append(Paragraph(line[3:], heading_style))
                elif line.startswith("# "):
                    story.append(Paragraph(line[2:], heading_style))
                elif line.strip() == "":
                    story.append(Spacer(1, 2 * mm))
                else:
                    story.append(Paragraph(line, normal_style))
            story.append(Spacer(1, 3 * mm))
        elif block.get("type") == "widget":
            wid = block.get("widget_id")
            w = widget_map.get(wid)
            if not w:
                story.append(Paragraph(f"[Widget {wid} not found]", small_style))
                continue
            title = w.get("title") or w.get("query") or wid
            story.append(Paragraph(title, heading_style))
            # Table only (chart image handled in dashboard_to_pdf)
            result = w.get("result")
            if result:
                table_data, _ = _table_data_from_result(result, max_rows=20)
                ncols = len(table_data[0])
                col_w = 174 * mm / max(ncols, 1)
                t = Table(
                    [[str(c)[:40] for c in row] for row in table_data],
                    colWidths=[col_w] * ncols,
                    repeatRows=1,
                )
                t.setStyle(
                    TableStyle(
                        [
                            ("BACKGROUND", (0, 0), (-1, 0), HexColor("#0f172a")),
                            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                            ("FONTSIZE", (0, 0), (-1, -1), 6.5),
                            ("GRID", (0, 0), (-1, -1), 0.4, HexColor("#e2e8f0")),
                            (
                                "ROWBACKGROUNDS",
                                (0, 1),
                                (-1, -1),
                                [colors.white, HexColor("#f8fafc")],
                            ),
                        ]
                    )
                )
                story.append(t)
            story.append(Spacer(1, 4 * mm))
        else:
            story.append(Paragraph(str(block), small_style))
    story.append(Spacer(1, 6 * mm))
    story.append(Paragraph("Generated by InsightAgent", small_style))
    doc.build(story)
    buf.seek(0)
    return buf
